### PR TITLE
Add Notepad widget to store notes

### PR DESCRIPTION
**Pull request by TXC**
Add Notepad widget to store notes.

Can be useful when some hubs don't support certain release groups, or add notes about users and so forth.

### CODE REVIEW

**Comment by maksis** [comment]
Thanks, a notepad widget is something that can be added. I'll test this tomorrow.

**Comment by maksis** [comment]
Quick note: could you remove translation strings for languages other than English? Translators could then translate them via https://www.transifex.com/airdcpp/airdcpp/dashboard/

I don't think that translations added in the repository are being synced to Transifex, so they would get removed (only the source language is being synced). I've also preferred no translation over machine translations.

**Comment by maksis** [comment]
Hmm, seems like the default notepad widget being created is currently crashing during rendering, as its settings object is empty (`{}`). I'd say that it would be better to use a different storage key for widget's own state and let the settings data to be modified only by the settings form (and widgets should also read their settings only via the settings object prop that is automatically being passed to them). There's a possible risk of getting out of sync and overwriting edited settings if the object is being loaded/saved from different places. You can check how the RSS widget is currently generating its cache key for the downloaded feeds: https://github.com/airdcpp-web/airdcpp-webui/blob/master/src/widgets/RSS/components/RSS.tsx#L129

**Comment by maksis** [comment]
I also realized that if widgets would save their state in local storage with their own custom property names, the data wouldn't get removed when the widget is removed (otherwise the widget should have some kind of deletion hook that would allow it to clear its state). Maybe there should be a generic key format for saving the widget state in local storage (such as `widgetid_state`). I can also implement the common code for that afterwards.

**Comment by maksis** [comment]
> Maybe there should be a generic key format for saving the widget state in local storage (such as `widgetid_state`)

Added in https://github.com/airdcpp-web/airdcpp-webui/commit/d97cd354c35be745ef6b615909b085633808c694

**Comment by TXC** [comment]
@maksis my thought with the localStorage and unique keys was to be able to use more than one instance of the widget to store different notes.

I'll take a look with your comments.

**Comment by maksis** [comment]
Merged. I'd still like to remove nesting the state inside a `widget` object as I don't think that it's really needed. `widget` exists for settings to separate widget-defined settings from common widget settings, but that is not needed here as the state object is fully managed by the widget itself. The resize handle of the `textarea` is probably something that could be hidden as the widget itself is resizable.

**Comment by TXC** [comment]
Hmm, the widget on the state object comes from the interface.
Can fix that one up!

The textarea resize handle is something the browser handles. Should look that one up!

Thanks for the merge!

Have lots of ideas.

**Comment by maksis** [comment]
If you are thinking of some kind of text formatting, https://github.com/airdcpp-web/airdcpp-webui/blob/master/src/components/TextDecorator.tsx might be worth of considering as it works for plain text (without markdown).

**Pull request merged**
